from pathlib import Path
path = Path("src/views/anagrafica/AnagraficaDetail.js")
text = path.read_text()
old = "                              <div className='d-flex gap-2 justify-content-end'>\n                                <CButton\n                                  color='secondary'\n                                  variant='outline'\n                                  size='sm'\n                                  type='button'\n                                  onClick={handleSedeCancel}\n                                  disabled={isSaving}\n                                >\n                                  Annulla\n                                </CButton>\n                                <CButton\n                                  color='primary'\n                                  size='sm'\n                                  type='button'\n                                  onClick={handleSedeSave}\n                                  disabled={isSaving}\n                                >\n                                  {isSaving ? 'Salvataggio...' : 'Salva'}\n                                </CButton>\n                              </div>"
new = "                              <div className='d-flex gap-2 justify-content-end'>\n                                <CButton\n                                  color='secondary'\n                                  variant='outline'\n                                  size='sm'\n                                  type='button'\n                                  onClick={handleSedeCancel}\n                                  disabled={isSaving}\n                                >\n                                  Annulla\n                                </CButton>\n                                {!isNewRow && sedeData && (\n                                  <CButton\n                                    color='danger'\n                                    variant='outline'\n                                    size='sm'\n                                    type='button'\n                                    onClick={() => handleSedeDelete(sedeData.id_sede)}\n                                    disabled={isSaving || savingSedeId === sedeData.id_sede}\n                                  >\n                                    {savingSedeId === sedeData.id_sede ? 'Eliminazione...' : 'Elimina'}\n                                  </CButton>\n                                )}\n                                <CButton\n                                  color='primary'\n                                  size='sm'\n                                  type='button'\n                                  onClick={handleSedeSave}\n                                  disabled={isSaving}\n                                >\n                                  {isSaving ? 'Salvataggio...' : 'Salva'}\n                                </CButton>\n                              </div>"
if old not in text:
    raise SystemExit('editing action block not found')
text = text.replace(old, new, 1)
path.write_text(text)
