from pathlib import Path
path = Path("backend/src/Service/AnagraficheService.php")
text = path.read_text()
old = "        $create = [];\n        $update = [];\n\n        if (array_key_exists('create', $payload)) {\n            if (!is_array($payload['create'])) {\n                throw new RuntimeException('Formato elenco sedi da creare non valido.', 422);\n            }\n\n            foreach ($payload['create'] as $index => $entry) {\n                if (!is_array($entry)) {\n                    throw new RuntimeException('Formato sede da creare non valido alla posizione ' . $index . '.', 422);\n                }\n\n                $create[] = $this->normaliseSedeFields($entry, true);\n            }\n        }\n\n        if (array_key_exists('update', $payload)) {\n            if (!is_array($payload['update'])) {\n                throw new RuntimeException('Formato elenco sedi da aggiornare non valido.', 422);\n            }\n\n            foreach ($payload['update'] as $index => $entry) {\n                if (!is_array($entry)) {\n                    throw new RuntimeException('Formato sede da aggiornare non valido alla posizione ' . $index . '.', 422);\n                }\n\n                $sedeId = $entry['id_sede'] ?? $entry['id'] ?? null;\n                if (!is_numeric($sedeId) || (int) $sedeId <= 0) {\n                    throw new RuntimeException('ID sede non valido.', 422);\n                }\n\n                $data = $this->normaliseSedeFields($entry, false);\n\n                if (!$data) {\n                    continue;\n                }\n\n                $update[] = [\n                    'id_sede' => (int) $sedeId,\n                    'data' => $data,\n                ];\n            }\n        }\n\n        return [\n            'create' => $create,\n            'update' => $update,\n        ];"
new = "        $create = [];\n        $update = [];\n        $delete = [];\n\n        if (array_key_exists('create', $payload)) {\n            if (!is_array($payload['create'])) {\n                throw new RuntimeException('Formato elenco sedi da creare non valido.', 422);\n            }\n\n            foreach ($payload['create'] as $index => $entry) {\n                if (!is_array($entry)) {\n                    throw new RuntimeException('Formato sede da creare non valido alla posizione ' . $index . '.', 422);\n                }\n\n                $create[] = $this->normaliseSedeFields($entry, true);\n            }\n        }\n\n        if (array_key_exists('update', $payload)) {\n            if (!is_array($payload['update'])) {\n                throw new RuntimeException('Formato elenco sedi da aggiornare non valido.', 422);\n            }\n\n            foreach ($payload['update'] as $index => $entry) {\n                if (!is_array($entry)) {\n                    throw new RuntimeException('Formato sede da aggiornare non valido alla posizione ' . $index . '.', 422);\n                }\n\n                $sedeId = $entry['id_sede'] ?? $entry['id'] ?? null;\n                if (!is_numeric($sedeId) || (int) $sedeId <= 0) {\n                    throw new RuntimeException('ID sede non valido.', 422);\n                }\n\n                $data = $this->normaliseSedeFields($entry, false);\n\n                if (!$data) {\n                    continue;\n                }\n\n                $update[] = [\n                    'id_sede' => (int) $sedeId,\n                    'data' => $data,\n                ];\n            }\n        }\n\n        if (array_key_exists('delete', $payload)) {\n            if (!is_array($payload['delete'])) {\n                throw new RuntimeException('Formato elenco sedi da eliminare non valido.', 422);\n            }\n\n            foreach ($payload['delete'] as $index => $value) {\n                if (!is_numeric($value) || (int) $value <= 0) {\n                    throw new RuntimeException('ID sede da eliminare non valido alla posizione ' . $index . '.', 422);\n                }\n                $delete[] = (int) $value;\n            }\n        }\n\n        return [\n            'create' => $create,\n            'update' => $update,\n            'delete' => $delete,\n        ];"
if old not in text:
    raise SystemExit('normalise block not found')
text = text.replace(old, new, 1)
path.write_text(text)
