from pathlib import Path
path = Path("backend/src/Repositories/AnagraficheRepository.php")
text = path.read_text()
insert_after = "    public function updateSede(int $anagraficaId, int $sedeId, array $data): void\n    {\n        $fields = $this->prepareSedeFields($data);\n\n        if (!$fields['assignments']) {\n            return;\n        }\n\n        $check = $this->pdo->prepare('SELECT 1 FROM tb_sedi WHERE id_sede = :sede AND id_anagrafica = :anagrafica LIMIT 1');\n        $check->bindValue(':sede', $sedeId, PDO::PARAM_INT);\n        $check->bindValue(':anagrafica', $anagraficaId, PDO::PARAM_INT);\n        $check->execute();\n\n        if ($check->fetchColumn() === false) {\n            throw new RuntimeException('Sede non associata all\\'anagrafica indicata.', 404);\n        }\n\n        if (array_key_exists('is_legale', $data) && (int) $data['is_legale'] === 1) {\n            $this->unsetSedeFlag($anagraficaId, 'is_legale', $sedeId);\n        }\n\n        if (array_key_exists('is_predefinita', $data) && (int) $data['is_predefinita'] === 1) {\n            $this->unsetSedeFlag($anagraficaId, 'is_predefinita', $sedeId);\n        }\n\n        $sql = 'UPDATE tb_sedi SET ' . implode(', ', $fields['assignments']) . ' WHERE id_sede = :id';\n        $statement = $this->pdo->prepare($sql);\n        $statement->bindValue(':id', $sedeId, PDO::PARAM_INT);\n\n        foreach ($fields['params'] as $placeholder => $value) {\n            $type = $fields['types'][$placeholder] ?? PDO::PARAM_STR;\n            $statement->bindValue($placeholder, $value, $type);\n        }\n\n        $statement->execute();\n    }\n\n"
if insert_after not in text:
    raise SystemExit('anchor not found')
addition = "    public function deleteSede(int $anagraficaId, int $sedeId): void\n    {\n        $check = $this->pdo->prepare('SELECT 1 FROM tb_sedi WHERE id_sede = :sede AND id_anagrafica = :anagrafica LIMIT 1');\n        $check->bindValue(':sede', $sedeId, PDO::PARAM_INT);\n        $check->bindValue(':anagrafica', $anagraficaId, PDO::PARAM_INT);\n        $check->execute();\n\n        if ($check->fetchColumn() === false) {\n            throw new RuntimeException('Sede non associata all\\'anagrafica indicata.', 404);\n        }\n\n        $delete = $this->pdo->prepare('DELETE FROM tb_sedi WHERE id_sede = :sede');\n        $delete->bindValue(':sede', $sedeId, PDO::PARAM_INT);\n        $delete->execute();\n    }\n\n"
text = text.replace(insert_after, insert_after + addition, 1)
path.write_text(text)
