from pathlib import Path
path = Path("src/views/anagrafica/AnagraficaDetail.js")
text = path.read_text()
old = "  const handleSedeDelete = async (sedeId) => {\n    if (!recordId || !sedeId) {\n      return\n    }\n\n    const confirmed = window.confirm('Confermi l\\'eliminazione della sede?')\n    if (!confirmed) {\n      return\n    }\n\n    setMutationError(null)\n    setSavingSedeId(sedeId)\n\n    try {\n      const response = await updateAnagraficaDetail({\n        token,\n        id: recordId,\n        sedi: { delete: [sedeId] },\n      })\n      handleMutationSuccess(response)\n      setEditingSedeId(null)\n      setSedeForm(null)\n    } catch (mutationErrorInstance) {\n      if (mutationErrorInstance.status === 401 && logout) {\n        logout()\n        return\n      }\n      setMutationError(mutationErrorInstance.payload?.message || mutationErrorInstance.message)\n    } finally {\n      setSavingSedeId(null)\n    }\n  }"
new = "  const handleSedeDelete = async (sedeId) => {\n    if (!recordId || !sedeId) {\n      return\n    }\n\n    const numericSedeId = Number(sedeId)\n    if (!Number.isFinite(numericSedeId) || numericSedeId <= 0) {\n      return\n    }\n\n    const confirmed = window.confirm('Confermi l\\'eliminazione della sede?')\n    if (!confirmed) {\n      return\n    }\n\n    setMutationError(null)\n    setSavingSedeId(numericSedeId)\n\n    try {\n      const response = await updateAnagraficaDetail({\n        token,\n        id: recordId,\n        sedi: { delete: [numericSedeId] },\n      })\n      handleMutationSuccess(response)\n      setEditingSedeId(null)\n      setSedeForm(null)\n    } catch (mutationErrorInstance) {\n      if (mutationErrorInstance.status === 401 && logout) {\n        logout()\n        return\n      }\n      setMutationError(mutationErrorInstance.payload?.message || mutationErrorInstance.message)\n    } finally {\n      setSavingSedeId(null)\n    }\n  }"
if old not in text:
    raise SystemExit('handleSedeDelete block not found')
text = text.replace(old, new, 1)
path.write_text(text)
