from pathlib import Path
path = Path("src/views/anagrafica/AnagraficaDetail.js")
text = path.read_text()
old = "                          <CTableDataCell className='text-end'>\n                            <CButton\n                              color='secondary'\n                              variant='outline'\n                              size='sm'\n                              onClick={() => handleSedeEdit(sedeData)}\n                              disabled={Boolean(editingSedeId)}\n                            >\n                              Modifica\n                            </CButton>\n                          </CTableDataCell>"
new = "                          <CTableDataCell className='text-end'>\n                            <div className='d-flex gap-2 justify-content-end'>\n                              <CButton\n                                color='secondary'\n                                variant='outline'\n                                size='sm'\n                                onClick={() => handleSedeEdit(sedeData)}\n                                disabled={Boolean(editingSedeId) || savingSedeId === sedeData.id_sede}\n                              >\n                                Modifica\n                              </CButton>\n                              <CButton\n                                color='danger'\n                                variant='outline'\n                                size='sm'\n                                onClick={() => handleSedeDelete(sedeData.id_sede)}\n                                disabled={Boolean(editingSedeId) || savingSedeId === sedeData.id_sede}\n                              >\n                                {savingSedeId === sedeData.id_sede ? 'Eliminazione...' : 'Elimina'}\n                              </CButton>\n                            </div>\n                          </CTableDataCell>"
if old not in text:
    raise SystemExit('non-edit actions block not found')
text = text.replace(old, new, 1)
path.write_text(text)
